/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controller.Controller;
import Modelo.Modelo;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Lencho-PC
 */
public class Vista1 extends javax.swing.JFrame implements Observer {

    private Controller elControl;
    private Modelo elModelo;

    
    
    public Vista1() {
        initComponents();
        this.setTitle("Editor de Formulas");
    }

    
    public void setController(Controller control){
        this.elControl=control;
    }
    public void setModel(Modelo elModelo){
        this.elModelo=elModelo;
        elModelo.addObserver(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        opcionEdicion = new javax.swing.JMenu();
        opcionArchivo = new javax.swing.JMenu();
        opcionNuevo = new javax.swing.JMenu();
        opcionAbrir = new javax.swing.JMenu();
        opcionGuardar = new javax.swing.JMenu();
        opcionSalir = new javax.swing.JMenu();
        opcionVista = new javax.swing.JMenu();
        herramientas = new javax.swing.JMenu();
        ventanas = new javax.swing.JMenu();
        ayuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );

        opcionEdicion.setText("Edición");
        jMenuBar1.add(opcionEdicion);

        opcionArchivo.setText("Archivo");
        opcionArchivo.setToolTipText("");

        opcionNuevo.setText("Nuevo ");
        opcionNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcionNuevoMouseClicked(evt);
            }
        });
        opcionNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionNuevoActionPerformed(evt);
            }
        });
        opcionArchivo.add(opcionNuevo);

        opcionAbrir.setText("Abrir...");
        opcionArchivo.add(opcionAbrir);

        opcionGuardar.setText("Guardar");
        opcionArchivo.add(opcionGuardar);

        opcionSalir.setText("Salir");
        opcionArchivo.add(opcionSalir);

        jMenuBar1.add(opcionArchivo);

        opcionVista.setText("Vista");
        jMenuBar1.add(opcionVista);

        herramientas.setText("Herramientas");
        jMenuBar1.add(herramientas);

        ventanas.setText("Ventanas");
        jMenuBar1.add(ventanas);

        ayuda.setText("Ayuda");
        jMenuBar1.add(ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionNuevoActionPerformed
     
    }//GEN-LAST:event_opcionNuevoActionPerformed

    private void opcionNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionNuevoMouseClicked
       Vista2 vista2 = new Vista2();
       vista2.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_opcionNuevoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ayuda;
    private javax.swing.JMenu herramientas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu opcionAbrir;
    private javax.swing.JMenu opcionArchivo;
    private javax.swing.JMenu opcionEdicion;
    private javax.swing.JMenu opcionGuardar;
    private javax.swing.JMenu opcionNuevo;
    private javax.swing.JMenu opcionSalir;
    private javax.swing.JMenu opcionVista;
    private javax.swing.JMenu ventanas;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
         //To change body of generated methods, choose Tools | Templates.
    }

}
